#### general settings
name: latent-reffusion-restore
use_tb_logger: true
model: latent_denoising
distortion: dehazing
# gpu_ids: [0]
gpu_ids: [0, 1, 2, 3, 4, 5, 6, 7]
dist: true  # 启用分布式训练

sde:
  max_sigma: 50
  T: 100
  sample_T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 1
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /codes/config/latent-restore/datasets/restore/trainH/GT512/
    dataroot_LQ: /codes/config/latent-restore/datasets/restore/trainH/LQ512/

    use_shuffle: true
    # n_workers: 8  # per GPU
    n_workers: 0  # per GPU
    n_workers: 2  # per GPU
    # batch_size: 8
    batch_size: 8
    GT_size: 512
    LR_size: 512
    use_flip: true
    use_rot: true
    use_swap: false
    color: RGB
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /codes/config/latent-restore/datasets/restore/testH/GT512/
    dataroot_LQ: /codes/config/latent-restore/datasets/restore/testH/LQ512/


#### network structures
network_G:
  which_model: ConditionalUT
  setting:
    img_channel: 8
    width: 16
    enc_blk_nums: [1, 1, 1, 1]
    middle_blk_num: 1
    dec_blk_nums: [1, 1, 1, 1]



network_L:
  which_model: UNet
  setting:
    in_ch: 1
    out_ch: 1
    ch: 8
    ch_mult: [4, 8, 8, 16]
    embed_dim: 8

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~
  pretrain_model_L: pretrained_models/1000_G.pth

#### training settings: learning rate scheme, loss
train:
  optimizer: Lion
  lr_G: !!float 3e-5
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 1e1 #1e4

#### logger
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 1e4
